### ISSUE TITLE
Feature request: Pretend accepting ads

### ISSUE THREAD

**Issue by hrasmussendk** [ghostery/ghostery-extension#339]
### Description

Feature request. Pretend accepting ads to avoid rejection of content

### Expected Behavior 

Some websites tests for ad blockers and if detected they reject to display their content. By pretending to accept the ads while actually blocking them, such websites would display their content to the user.

### Steps to Reproduce

Nothing to reproduce since it's a request of a new feature.

**Comment by remusao** [comment]
Hi @hrasmussendk and thank you for reaching out!

Avoiding so-called "adwalls" is a very interesting topic and something that we are continuously working on. There are already a lot of websites which would show you such warnings or prevent you from seeing their content completely but do not thanks to Ghostery. There are some improvements coming in next release as well regarding this.

If you see specific websites preventing you from accessing the content or showing you warnings while the adblocker is enabled, would you maybe share them with us so that we can work on improving the user experience there?

Thanks a lot!

**Comment by maverick74** [comment]
@remusao I found this one: 

https://www.washingtonpost.com/world/asia_pacific/chinas-huawei-says-it-has-long-prepared-for-americas-assault/2019/05/21/04b29c60-7bc2-11e9-b1f3-b233fe5811ef_story.html?noredirect=on&utm_term=.4d1557962d6f

Would you like that every website one finds be reported back to you here?

**Comment by remusao** [comment]
@maverick74 Thanks for reporting these, that is very helpful for us. For now we will be using this issue tracker for adblocker issues as well. I just created an `adblocker` label which we can use to tag such issues. In the future, would you mind opening an issue whenever you encounter such issue so that we can keep the discussion focused on specific sites? (since it might be different issues). I will have a look at the two cases you reported!

**Comment by grgnday** [comment]
Hi, wanted to report an issue as this seems like the place to do so. [Rock Paper Shotgun](https://www.rockpapershotgun.com/2020/03/24/half-life-alyx-gordon-freeman/) was asking to turn off ad blocker for some time, but we could just close their popup. Now it seems we can't. I also want to learn if this is considered a paywall...

**Comment by remusao** [comment]
> Hi, wanted to report an issue as this seems like the place to do so. [Rock Paper Shotgun](https://www.rockpapershotgun.com/2020/03/24/half-life-alyx-gordon-freeman/) was asking to turn off ad blocker for some time, but we could just close their popup. Now it seems we can't. I also want to learn if this is considered a paywall...

@grgnday could you tell me which browser you are using at the moment please?

**Comment by grgnday** [comment]
Firefox 74, the latest stable with Ghostery 8.4.6

**Comment by remusao** [comment]
@grgnday I see, it seems like this is not happening on the latest version of the adblocker, but on Firefox our latest update has been delayed so it will only be pushed in a few days. Once it's deployed this issue should be resolved.

**Comment by grgnday** [comment]
@remusao Alright, thanks! Just one thing though, is there a specific reason for Firefox versions to be published after other browsers in general like deploying hotfixes?

**Comment by remusao** [comment]
> @remusao Alright, thanks! Just one thing though, is there a specific reason for Firefox versions to be published after other browsers in general like deploying hotfixes?

The review process is different depending on the browser and in this case we have to make some minor tweaks and submit again for review. This happens sometimes and we do our best to be reactive in such cases. Hopefully this will not take long!

**Comment by ygzdrmz** [comment]
I suppose the update still isn't published? I have those warnings on RPS as well.
![Screenshot_2020-04-01 You can be a baby in Mount Blade 2 Bannerlord](https://user-images.githubusercontent.com/62989861/78123341-b00d8500-7416-11ea-896e-f19c8d7bf1cd.png)

**Comment by remusao** [comment]
@ygzdrmz Unfortunately yes, we are still pending on approval for the AMO store. I double-checked and the issue on this website is fixed on the Chrome version as well as in Cliqz browser so it's just a matter of time until approval now. @christophertino will now better about the latest status of this process.

**Comment by ygzdrmz** [comment]
Thanks for the quick response. For other browsers though, I want to stick with Firefox (Gecko) so can't really say that I care other than I'm a little sad that Firefox is getting these updates the last and other browsers are all against Mozilla.

**Comment by grgnday** [comment]
Hey @ygzdrmz, I understand your frustration with the current state of browsers but its funny that you say those to people that work at Ghostery/Cliqz. 

I highly doubt they don't care about Firefox since [they have a pretty good relationship with Mozilla](https://blog.mozilla.org/press-uk/2016/08/23/mozilla-makes-strategic-investment-in-cliqz-to-enable-privacy-focused-search-innovation/). They can't just tell them to hurry up with their approval and I would advise you to check out what Cliqz Browser is before saying that you want to stick with or support Gecko. Its based on Firefox and all their work is also open-source which means Mozilla can benefit from their work if they want to. 

Lastly, I share your opinion that a non-profit should build the browser but you should really check out Cliqz Browser as it's like a supercharged Firefox that is.. well simply a better/more ethical Brave Browser. To be honest their work shows that they do more for user privacy (at least for the short-term) than Mozilla who _can be_ too scared that Google will get angry with their position from time to time.

**Comment by ygzdrmz** [comment]
Wow I didn't know these. Sorry for commenting without knowing. Can I use Ghostery with Cliqz?

**Comment by remusao** [comment]
> Wow I didn't know these. Sorry for commenting without knowing. Can I use Ghostery with Cliqz?
> 
> Edit: Yes I can!

@ygzdrmz You can, but keep in mind that the same adblocking and anit-tracking features are also built-in the Cliqz browser, and that the issue with Ghostery not being released to AMO also impacts Cliqz since the extensions you can install are from the same AMO store than Firefox. This means that the adblocker issue might still impact you unless you stick with Cliqz' built-in adblocker and antitracking for now.

**Comment by ygzdrmz** [comment]
Alright I paused it for now. While waiting for the update it is a good time to try out Cliqz Browser :D

**Comment by christophertino** [comment]
Just to clarify how our releases work: I push Ghostery updates to Firefox, Chrome, Opera and Edge stores all at the same time. Firefox does an in-depth, manual code review of our releases which generally takes about a week, often longer if they request changes. That's why our FF updates take a bit more time to publish.

**Comment by smalluban** [comment]
Feel free to re-open if the issue is still valid. The only platform that is still on the v8 version is Firefox.

**Comment by maverick74** [comment]
so @smalluban , what will be the behavior???

Will it just pretend to accept? 
Will it accept and click (like [adnauseam](https://addons.mozilla.org/en-US/firefox/addon/adnauseam/), for example )?

Can you elaborate more about the feature?

thank you

**Comment by smalluban** [comment]
Ghostery is based on community-created filters, which block ads, requests, etc.. We maintain the TrackerDB and fixes for found broken pages (not adblocker walls), which is faster or the only way to fix, as the community list maintainers don't respond or refuse to add the fix.

If the page detects adblocker, it means, that it detects the filter created by the community. It's in our current scope to provide special behaviors to try to "block the blockers".

**Comment by maverick74** [comment]
> Ghostery is based on community-created filters, which block ads, requests, etc.. We maintain the TrackerDB and fixes for found broken pages (not adblocker walls), when it is faster or the only way to fix, as the community list maintainers don't respond or refuse to add the fix.
> 
> If the page detects adblocker, it means, that it detects the filter created by the community. It isn't in our current scope to provide special behaviors to try to "block the blockers".

I'm sorry! I didn't understand (probably because, English is not my native language...)

Ghostery will pretend to accept ads (as the task was closed as **_completed_**).

Now, if you were an ad publisher what feedback are you suppose to have?

- The ad was just shown?
- The ad was clicked?
- ...

A bit off-topic (since you mentioned it)
I would also like to know why Firefox version is kept on v8?

thank you

**Comment by smalluban** [comment]
> Now, if you were an ad publisher what feedback are you suppose to have?

Sorry, I just can't get what you would like to know. Can you explain how this question relates to the Ghostery extension?

> I would also like to know why Firefox version is kept on v8?

It's the last platform to migrate. The code is ready, but we do it gradually platform by platform to provide the best user experience to our users. The V10 should be live on Firefox soon.

**Comment by maverick74** [comment]
> Sorry, I just can't get what you would like to know. Can you explain how this question relates to the Ghostery extension?

ahah. It's Nothing important!
But lets go step by step.

You closed this as **completed**, so i understand that in the next version the ghostery extension will start to **pretend to accept ads**.

in other words, to an ad publisher (e.g.: google) when they try to show "ghostery users" an ad - that the ghostery extension will block - instead of the publisher knowing that the ad was blocked, they will think it was shown to the user successfully.

(that is what i think this feature is all about!)

Now, my question is: will the ad publisher think the ad was just "shown", or do they think the ad was also "clicked"?

hope i was clear enough... :)

**Comment by smalluban** [comment]
The issue is automatically moved to completed when closed, regardless of the resolution. This is GitHub projects feature. It only happened because the issue was added to one of the boards. It's not "completed" if you wonder.

**Comment by chrmod** [comment]
Hi @maverick74 - thank you contributing to Ghostery with ideas and comments. We much appreciate it!

This particular topic has at least two layers:
1. Helping users access content guarded by so called adwalls
2. Clicking on ads

Adwalls, is something we actively research and may bring some solutions for in the future.

Clicking on ads however, is something that no content blocker should try to do, for various reasons. Few that are most pressing:
* clicking on an ad implies a cost to advertisers, and profit for publisher - so when automated this is clearly a fraud and ad system will penalties both parties
* automated clicking may be detected as bot activity, so user may be lock out from content
* automated clicking is not a guarantee to grant access to content. We see that typical adwall is deployed when a tracking script is blocked. 

Hope this clarifies the matter.

Hope to hear more feedback from you @maverick74 !

**Comment by maverick74** [comment]
> Hope this clarifies the matter.

Yes, it does!

Thank you for your clarifying reply :).

It's great to know your vision of it!
